
---
title: 'Informe: Comparación de longitud de pétalo de Iris (versicolor vs virginica)'
author: "Andrea Luna Vasconcelos"
date: "2025-09-05"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(ggplot2)
```


Planteamiento del problema
En este caso se analiza la longitud de pétalo entre las especies versicolor y virginica.
 H0 = No existe diferencia significativa en la longitud de pétalos entre versicolor y virginica.
 H1 = Sí existe una diferencia significativa en la longitud de pétalos entre versicolor y virginica.``{r setup, include=FALSE}
# Carga de datos
data("iris")
dat_iris <- subset(iris, Species %in% c("versicolor", "virginica"))
dat_iris$Species <- droplevels(dat_iris$Species)

versicolor <- subset(dat_iris, Species == "versicolor")$Petal.Length
virginica  <- subset(dat_iris, Species == "virginica")$Petal.Length
dat_sub <- dat_iris
# QQ-plots para normalidad
par(mfrow=c(1,2))
qqnorm(versicolor); qqline(versicolor)
qqnorm(virginica); qqline(virginica)
par(mfrow=c(1,1))

# Prueba Shapiro-Wilk
shapiro_versicolor <- shapiro.test(versicolor)
shapiro_virginica <- shapiro.test(virginica)

# Varianza
var_test <- var.test(versicolor, virginica)

# t de student
t_result <- t.test(versicolor, virginica, alternative = "two.sided", var.equal = TRUE)

# Resultados de la prueba t:

t = r round(t_result$statistic,2)

df = r t_result$parameter

p-value = r signif(t_result$p.value,3)

Medias: Versicolor = r round(mean(versicolor),2) cm, Virginica = r round(mean(virginica),2) cm

Como p < 0.05, se rechaza H0 y se concluye que existe una diferencia significativa en la longitud de pétalos entre las especies.

# Efecto Cohen´s

cohens_efecto <- function(x, y) {
  n1 <- length(x); n2 <- length(y)
  s1 <- sd(x); s2 <- sd(y)
  sp <- sqrt(((n1 - 1) * s1^2 + (n2 - 1) * s2^2) / (n1 + n2 - 2))
  (mean(x) - mean(y)) / sp
}
d1_cal <- cohens_efecto(versicolor, virginica)
d1_cal

# Visualización de datos

print(
  ggplot(dat_sub, aes(x = Species, y = Petal.Length, fill = Species)) +
    geom_violin(trim = FALSE, color = "black", alpha = 0.6) + 
    geom_boxplot(width = 0.1, fill = "white", outlier.shape = NA) +
    stat_summary(fun = mean, geom = "point", shape = 23, size = 3, fill = "red") +
    theme_minimal() +
    labs(title = "Distribución de la longitud de pétalos por especie",
         x = "Especie",
         y = "Longitud de pétalo (cm)") +
    theme(legend.position = "none",
          plot.title = element_text(hjust = 0.5, size=14, face="bold"),
          axis.title=element_text(size=12))
)
  
# Interpretación biológica

Los resultados muestran que Virginica presenta pétalos significativamente más largos que Versicolor.
El tamaño del efecto muy grande (Cohen's d = r round(d1_cal,2)) indica que la diferencia es relevante biológicamente.
Esto puede estar asociado a estrategias de adaptación reproductiva, ya que pétalos más grandes atraen más polinizadores y mejoran la absorción de luz ultravioleta, aumentando la visibilidad de la flor y favoreciendo la reproducción.


